version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pairing-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k60jre37mi3b"
s3_prefix = "pairing-bot"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
